security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: root
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: 127.0.0.1
      username: user
      password: root
      database: piggymetrics
      port: 27017

server:
  context-path: /statistics
  port: 7000

rates:
  url: http://api.fixer.io